name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  drive-credentials:  # id of input
    description: 'Base64 json of your drive credentials'
    required: true
    default: ''
  drive-folder-id:  # id of input
    description: 'Drive folder id to uplaod the files'
    required: true
    default: ''
  folder-to-upload:  # id of input
    description: 'Folder of your project to upload to drive'
    required: true
    default: ''
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'